### ISSUE TITLE
Bug ngab

### ISSUE THREAD

**Issue by Mx-Shimmer-01** [ilmanhdyt/ShiraoriBOT-Md#38]
TypeError: Cannot read properties of undefined (reading 'me')
2022-02-22T04:04:35.473160+00:00 app[web.1]:     at Object.get user [as user] (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:465:36)
2022-02-22T04:04:35.473161+00:00 app[web.1]:     at Object.makeGroupsSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:23:5)
2022-02-22T04:04:35.473161+00:00 app[web.1]:     at Object.makeMessagesSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:15:27)
2022-02-22T04:04:35.473162+00:00 app[web.1]:     at Object.makeChatsSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:13:34)
2022-02-22T04:04:35.473162+00:00 app[web.1]:     at Object.makeMessagesRecvSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:26:26)
2022-02-22T04:04:35.473162+00:00 app[web.1]:     at makeWASocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/index.js:6:51)
2022-02-22T04:04:35.473163+00:00 app[web.1]:     at Object.exports.makeWASocket (/app/lib/simple.js:21:16)
2022-02-22T04:04:35.473163+00:00 app[web.1]:     at Object.<anonymous> (/app/main.js:76:22)
2022-02-22T04:04:35.473164+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
2022-02-22T04:04:35.473165+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
2022-02-22T04:04:35.482174+00:00 app[web.1]: Exited with code: 1

**Comment by Mx-Shimmer-01** [comment]
Gak di respon pelit
